export const projects=[{
  id:"0",
  projectName:"Project 1",
  projectDescription:"Project 1 Description",
  projectType:"Project 1 Type",
},
{
  id:"1",
  projectName:"Project 2",
  projectDescription:"Project 2 Description",
  projectType:"Project 2 Type",
},
{
  id:"2",
  projectName:"Project 3",
  projectDescription:"Project 3 Description",
  projectType:"Project 3 Type",
},
{
  id:"3",
  projectName:"Project 4",
  projectDescription:"Project 4 Description",
  projectType:"Project 4 Type",
},
{
  id:"4",
  projectName:"Project 5",
  projectDescription:"Project 5 Description",
  projectType:"Project 5 Type",
},
{
  id:"5",
  projectName:"Project 6",
  projectDescription:"Project 6 Description",
  projectType:"Project 6 Type",
},
{
  id:"6",
  projectName:"Project 7",
  projectDescription:"Project 7 Description",
  projectType:"Project 7 Type",
},
{
  id:"7",
  projectName:"Project 8",
  projectDescription:"Project 8 Description",
  projectType:"Project 8 Type",

},
{
  id:"8",
  projectName:"Project 9",
  projectDescription:"Project 9 Description",
  projectType:"Project 9 Type",
},
{
  id:"9",
  projectName:"Project 10",
  projectDescription:"Project 10 Description",
  projectType:"Project 10 Type",
},
{
  id:"10",
  projectName:"Project 11",
  projectDescription:"Project 11 Description",
  projectType:"Project 11 Type",
},
{
  id:"11",
  projectName:"Project 12",
  projectDescription:"Project 12 Description",
  projectType:"Project 12 Type",
},
{
  id:"12",
  projectName:"Project 13",
  projectDescription:"Project 13 Description",
  projectType:"Project 13 Type",
},
{
  id:"13",
  projectName:"Project 14",
  projectDescription:"Project 14 Description",
  projectType:"Project 14 Type",
},
{
  id:"14",
  projectName:"Project 15",
  projectDescription:"Project 15 Description",
  projectType:"Project 15 Type",
},
{
  id:"15",
  projectName:"Project 16",
  projectDescription:"Project 16 Description",
  projectType:"Project 16 Type",
},
{
  id:"16",
  projectName:"Project 17",
  projectDescription:"Project 17 Description",
  projectType:"Project 17 Type",
},
{
  id:"17",
  projectName:"Project 18",
  projectDescription:"Project 18 Description",
  projectType:"Project 18 Type",
},
{
  id:"18",
  projectName:"Project 19",
  projectDescription:"Project 19 Description",
  projectType:"Project 19 Type",
},
{
  id:"19",
  projectName:"Project 20",
  projectDescription:"Project 20 Description",
  projectType:"Project 20 Type",
},
{
  id:"20",
  projectName:"Project 21",
  projectDescription:"Project 21 Description",
  projectType:"Project 21 Type",
},
{
  id:"21",
  projectName:"Project 22",
  projectDescription:"Project 22 Description",
  projectType:"Project 22 Type",
},
{
  id:"22",
  projectName:"Project 23",
  projectDescription:"Project 23 Description",
  projectType:"Project 23 Type",
},
{
  id:"23",
  projectName:"Project 24",
  projectDescription:"Project 24",
  projectType:"Project 24 Type",
}
]
